apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Ejemplo-deploy-techdocs
  description: The place to be, for great artists
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: Angel Allepuz
